install:
- sudo apt-get update
- sudo apt-get install haskell-platform texlive texlive-xetex texlive-latex-extra
- git clone "https://github.com/jgm/pandoc.git"
- cd pandoc
- git submodule update --init data/templates/
- cabal update
- cabal install --only-dependencies pandoc
- cabal install
- PATH=$HOME/.cabal/bin:$PATH
- cd ..

before_script:
- pandoc -v

script: make

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GCdvpv99K+v9fC+8nsYqIc+CoHvQBupavQKyDA2qv/qVQ+StJvE58gkAyZxsa+U8p5L00bigqShtpgvyoGnZlPvPB71SHhrnx5GM0cy3UuP8EoRqvzqpVb7/mSwTfEBKR5LkJUqIYYEhoiUsXoGjETsVk69E2O16dz03UXMk/PI=
  file: 
  - java-notes.pdf
  - swift-notes.pdf
  on:
    tags: true
    all_branches: true
