install:
- sudo apt-get update
- sudo apt-get install haskell-platform texlive
- wget "https://github.com/jgm/pandoc/archive/1.13.1.tar.gz"
- tar xvf 1.13.1.tar.gz
- cd pandoc-1.13.1
- cabal update
- cabal install --only-dependencies pandoc
- cabal install

before_script:
- pandoc -v

script: make

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GCdvpv99K+v9fC+8nsYqIc+CoHvQBupavQKyDA2qv/qVQ+StJvE58gkAyZxsa+U8p5L00bigqShtpgvyoGnZlPvPB71SHhrnx5GM0cy3UuP8EoRqvzqpVb7/mSwTfEBKR5LkJUqIYYEhoiUsXoGjETsVk69E2O16dz03UXMk/PI=
  file: notes.pdf
  on:
    tags: true
    all_branches: true
