install:
- sudo apt-get update
- sudo apt-get install cabal-install texlive
- cable sandbox init
- cabal update
- cabal install install -j --disable-documentation -fhttps pandoc

script: make

before_script:
- pandoc -v

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GCdvpv99K+v9fC+8nsYqIc+CoHvQBupavQKyDA2qv/qVQ+StJvE58gkAyZxsa+U8p5L00bigqShtpgvyoGnZlPvPB71SHhrnx5GM0cy3UuP8EoRqvzqpVb7/mSwTfEBKR5LkJUqIYYEhoiUsXoGjETsVk69E2O16dz03UXMk/PI=
  file: notes.pdf
  on:
    tags: true
    all_branches: true
